### ISSUE TITLE
More lenient treatment of entries.timings.receive

### ISSUE THREAD

**Issue by possiblywrong** [ericduran/chromeHAR#10]
Some recording proxies, e.g. browsermob, omit the timings object for entries which have encountered certain failure modes. (reading the spec, this is ambiguous behaviour, HAR tools _may_ be at liberty to omit this...open to debate IMO)

chromeHAR could be more lenient with this behaviour in mind.

Suggesting that we go for the default of 0 in this case for receive, for a HAREntry.

**Comment by ericduran** [comment]
:)

Thanks.
