### ISSUE TITLE
Licensing needs clarification

### ISSUE THREAD

**Issue by possiblywrong** [ericduran/chromeHAR#12]
To smooth and encourage contributions, can the license of the project be stated and provenance of code confirmed? i.e. which bits come from Chrome and other places.

**Comment by ericduran** [comment]
This commit should should solve this issue https://github.com/ericduran/chromeHAR/commit/2aa131d067b404caf952000ae4e52a84860bf0a1

GPL v2, for compatibility with the webkit parts.
