### ISSUE TITLE
Project needs master branch

### ISSUE THREAD

**Issue by possiblywrong** [ericduran/chromeHAR#17]
Mostly so we can maintain a version without the GitHub banner and Google Analytics, but it would also be helpful given how hardwired 'master' is when typing Git commands.

**Comment by ericduran** [comment]
Hmm, I tend to avoid master branches on github pages site.

That being said, I'm ok with a master branch if you need it for your local version.

**Comment by possiblywrong** [comment]
I've softened a little here. It boils down to whether this repo or mine maintains the without banner and analytics. I'd be happy to do this if you want.

Philosophically, I'd say that the canonical project does not have hosting specific code in it. BTW I'm not necessarily seeing this as a site, more an embeddable component(you may get some pulls to that effect shortly, when I figure out the best approach).

**Comment by ericduran** [comment]
Yep. That makes sense. I'll create a master branch.
