### ISSUE TITLE
Add @cvan as a contributor 

### ISSUE THREAD

**Issue by ericduran** [ericduran/chromeHAR#58]
Hey @cvan,

I went ahead and added you as a contributor.

Also I appreciate all the work you've done on the project. Figure I'll open an issue just  so I'll have somewhere to communicate this with you. 

I guess you can now close this ticket when ever. 

Ha also no pressure. But you have been reviewing PRs so you should also be able to merge them :wink:  

Thanks.

**Comment by cvan** [comment]
thanks, appreciate it - cheers!  :beers:
