### ISSUE TITLE
Load HAR from URL

### ISSUE THREAD

**Issue by BlackthornYugen** [ericduran/chromeHAR#67]
I like to through har files on my pastebin account; it would be nice if they could be loaded directly.

It would be really handy if you could share a HAR with a link like this:  http://ericduran.github.io/chromeHAR/http%3A%2F%2Fpastebin.com%2Fxxxxxxx

Or maybe just give the option to paste json into a textarea?

**Edit** Found that [cvan](/cvan) already added [this feature](/ericduran/chromeHAR/commit/b2a2a3e552bcb708db5c6e483bca501e40cd1881) but it doesn't look like I can use pastebin because of cross site stuff. [My Attempt to use pastebin](http://ericduran.github.io/chromeHAR/?url=http://pastebin.com/raw.php?i=kLun7FhC)

**Comment by cvan** [comment]
[pastebin.com](http://pastebin.com/) should be serving that with [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

I would suggest contacting [pastebin.com](http://pastebin.com/) or a CORS'd service such as [dpaste.com](http://dpaste.com/):

http://ericduran.github.io/chromeHAR/?url=http://dpaste.com/2R2Q1KM.txt

<hr>

an alternative is to use a service like https://jsonp.nodejitsu.com/ (or add a server as a dependency) as a proxy for `GET requests` to add CORS headers. but that's hacky and not worth the maintenance headache IMO.
